# image:https://hub.docker.com/_/phpmyadmin
# db container for test

version: "3.8"
services:
  phpmyadmin:
      image: phpmyadmin:$APP_VERSION
      container_name: $APP_NAME
      environment:
       - PMA_ARBITRARY=1
       - PMA_ABSOLUTE_URI=$APP_URL
       - UPLOAD_LIMIT=$APP_UPLOAD_LIMIT
      restart: always
      ports:
       - ${APP_HTTP_PORT}:80

  db:
    image: mariadb:10.3
    container_name: $APP_NAME-db
    restart: always
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    profiles:
      - db

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  db:
